test("First test", () => {
    throw new Error("Panic!");
});